### ISSUE TITLE
Segfault when decompressing paired end file to fastq, but only one fastq provided

### ISSUE THREAD

**Issue by shubhamchandak94** [mitogen/genie#13]
**Describe the bug**
When I compressed paired end unaligned data and then decompressed it with a fastq file in the --output-file option (and no --output-suppl-file option), genie ended with segmentation fault. The error happens because of this code: https://github.com/mitogen/genie/blob/develop/src/genie/format/fastq/exporter.cc#L71, which increments/decrements the pointer in the vector of files without checking if two output files are provided.

**To Reproduce**
1. ./build/bin/genie run -i data/fastq/fourteen-records.fastq --input-suppl-file data/fastq/fourteen-records-pair.fastq -o output.mgb
2. ./build/bin/genie run -i output.mgb -o decompressed.fastq

**Expected behavior**
I think the program should give an invalid option error in this case. It will not be correct to just output everything to one file, because then it is not possible to distinguish between the forward and reverse read.

**Environment (please complete the following information):**
 - OS: macOS
 - OS version 10.15.6
 - Compiler GCC
 - Compiler version 8.4.0

**Comment by Junaiid-Ahmad** [comment]
Alternatively, maybe one of the following should be done:

-- output interleaved fastq if only one output file is provided, or
-- automatically generate two output files decompressed.1.fastq and
decompressed.2.fastq

Best,
Junaid

**Comment by shubhamchandak94** [comment]
I think the first option you suggest has issues when the pairs are not combined while decoding. Then the interleaving will not allow us to recover which read came from file 1 and which read came from file 2. 
The second option seems better to me. A minor issue is that we don't know whether the data is single end or paired end when parsing the program options and creating the file ([here](https://github.com/mitogen/genie/blob/develop/src/apps/genie/run/program-options.cc#L213) and [here](https://github.com/mitogen/genie/blob/develop/src/apps/genie/run/main.cc#L93)). One way out of this is to always generate two files, even when the data is single end, but that's not ideal.

**Comment by Junaiid-Ahmad** [comment]
On Fri, 31 Jul 2020 at 12:16, Shubham Chandak <notifications@github.com>
wrote:

> I think the first option you suggest has issues when the pairs are not
> combined while decoding. Then the interleaving will not allow us to recover
> which read came from file 1 and which read came from file 2.
>
Yes, to generate interleaved fastq file "with proper ordering of paired
reads", post-processing to combine pairs after decoding would be needed.
But if if the proper ordering is not required, then it would be a simple
writing of both paired and split reads (in arbitrary order) to the output
file.

> The second option seems better to me. A minor issue is that we don't know
> whether the data is single end or paired end when parsing the program
> options and creating the file (here
> <https://github.com/mitogen/genie/blob/develop/src/apps/genie/run/program-options.cc#L213>
> and here
> <https://github.com/mitogen/genie/blob/develop/src/apps/genie/run/main.cc#L93>).
> One way out of this is to always generate two files, even when the data is
> single end, but that's not ideal.
>
I think it can be checked from field on number of template segments
(present in the parameter set I think - to be checked), if the mpegg file
contains paired records or not. Based on that, files can be created
accordingly.

**Comment by shubhamchandak94** [comment]
Thanks Junaid. I have done the following on feature/paired-end branch. Whenever I encounter a record with number of template segments = 2 but number of fastq files is only 1, I write the segments to the single file, but add a suffix of /1 or /2 to denote whether these reads are the "first" read in the pair. In other cases, nothing changes and this suffix is not added.
See [commit](https://github.com/mitogen/genie/commit/fb3489cc0979f69d82add98c603af1ec27c0f761#diff-e781ff0ff6adc0769c54a46d4148187c).
