### ISSUE TITLE
Compilation error "non-constexpr constructor cannot be used in a constant expression"

### ISSUE THREAD

**Issue by shubhamchandak94** [mitogen/genie#14]
**Describe the bug**
I get a compilation error in src/genie/core/constants.h when compiling with Apple Clang (develop branch). The errors are on basically every line in struct GenSub (starting at line 59) and look like:

constants.h:59:34: error: constexpr variable 'POS_MAPPING_FIRST' must be initialized by a constant expression
    static constexpr GenSubIndex POS_MAPPING_FIRST = {GenDesc::POS, 0};
                                 ^                   ~~~~~~~~~~~~~~~~~
constants.h:59:54: note: non-constexpr constructor 'pair<genie::core::GenDesc, int, false>' cannot be used in a constant expression
    static constexpr GenSubIndex POS_MAPPING_FIRST = {GenDesc::POS, 0};
                                                     ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:444:5: note: declared here
    pair(_U1&& __u1, _U2&& __u2)

**To Reproduce**
1. git checkout develop
2. mkdir build && cd build
3. cmake ..
4. make

**Environment (please complete the following information):**
 - OS: macOS
 - OS version 10.14.6
 - Compiler AppleClang
 - Compiler version 12.0.0.12000026

**Additional context**

**Comment by MueFab** [comment]
Seems that std::pair constructors are only constexpr in c++14 and later. I changed it to regular const and the compilation errors should be gone now.

**Comment by shubhamchandak94** [comment]
Thanks, the compilation works now with clang on Mac. The build with openmp still doesn't work probably because cmake can't detect it with Apple clang, but we can try to fix that later.
