### ISSUE TITLE
Genie gets stuck when decompressing unaligned data mgb to mgrec format

### ISSUE THREAD

**Issue by shubhamchandak94** [mitogen/genie#15]
**Describe the bug**
When I compressed a paired end file with genie (spring) and then decompressed to mgrec format, genie got stuck. It works nicely when decompressing to fastq. I tried to debug with gdb/lldb and found that the program was stuck at some pthread join function (exact gdb/lldb backtrace pasted at the end) (debugging done with both 1 and 8 threads).

**To Reproduce**
1. git checkout develop
2. mkdir build && cd build
3. curl ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR554/SRR554369/SRR554369_1.fastq.gz -o SRR554369_1.fastq.gz
4. curl ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR554/SRR554369/SRR554369_2.fastq.gz -o SRR554369_2.fastq.gz
5. gunzip SRR554369_1.fastq.gz SRR554369_2.fastq.gz
6. ./bin/genie run -i SRR554369_1.fastq --input-suppl-file SRR554369_2.fastq -o tmp.mgb -f
7. ./bin/genie run -i tmp.mgb -o tmp.mgrec -f

**Environment (please complete the following information):**
 - OS: Ubuntu
 - OS version 18.04.4 LTS
 - Compiler GCC
 - Compiler version 7.4.0

Note: Same thing happens on Mac with GCC 8.4.0.

**Additional context**
Conditions for this happening:
1. Also happens when compiled with openmp and using 1 or more threads. 
2. Does not happen when I compress only single file SRR554369_1.fastq. 
3. Does not happen when I decompress to two fastq files (or to interleaved fastq when in feature/paired-end branch) 

gdb on Ubuntu:
#0  0x00007ffff7bbed2d in __GI___pthread_timedjoin_ex (threadid=140737331406592, thread_return=0x0, abstime=0x0,
    block=<optimized out>) at pthread_join_common.c:89
#1  0x00007ffff76bb8c3 in std::thread::join() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x0000555555adb3ec in genie::util::ThreadManager::run (this=0x555555ecc7b8)
    at /raid/shubham/genie/src/genie/util/thread-manager.cc:60
#3  0x0000555555b7a63d in genie::core::FlowGraphDecode::run (this=0x555555ecc7b0)
    at /raid/shubham/genie/src/genie/core/flowgraph-decode.cc:179
#4  0x00005555558ad358 in genieapp::run::main (argc=9, argv=0x7fffffffe250) at /raid/shubham/genie/src/apps/genie/run/main.cc:271
#5  0x000055555588f01c in main (argc=10, argv=0x7fffffffe248) at /raid/shubham/genie/src/apps/genie/main.cc:43

lldb on Mac: 
  * frame #0: 0x00007fff67b0155e libsystem_kernel.dylib`__ulock_wait + 10
    frame #1: 0x00007fff67bc45c2 libsystem_pthread.dylib`_pthread_join + 347
    frame #2: 0x0000000100fd7843 libstdc++.6.dylib`std::thread::join() + 19
    frame #3: 0x000000010025cea6 genie`genie::util::ThreadManager::run(this=0x0000000101504148) at thread-manager.cc:60:15
    frame #4: 0x00000001002c0428 genie`genie::core::FlowGraphDecode::run(this=0x0000000101504140) at flowgraph-decode.cc:179:12
    frame #5: 0x0000000100016f87 genie`genieapp::run::main(argc=9, argv=0x00007ffeefbff890) at main.cc:271:19
    frame #6: 0x0000000100009d39 genie`main(argc=10, argv=0x00007ffeefbff888) at main.cc:43:32
    frame #7: 0x00007fff679becc9 libdyld.dylib`start + 1
    frame #8: 0x00007fff679becc9 libdyld.dylib`start + 1

**Comment by MueFab** [comment]
Should be fixed now.

**Comment by shubhamchandak94** [comment]
Thanks, will check tomorrow and update the feature/paired-end branch
