### ISSUE TITLE
Regarding conversion of SAM to MPEG-G

### ISSUE THREAD

**Issue by Abby3017** [mitogen/genie#6]
Thanks for creating such a great tool to leverage the advantages of MPEG-G specification. I have few queries regarding this tool -
1. Does Genie support conversion of SAM/BAM format to genie ??
2. As it is mentioned it take unaligned input data in format of FASTQ or FASTA is there any future roadmap to support alignment of data in the output using reference genome data ??

**Comment by voges** [comment]
Thanks for your comments!
1: Genie is still work in progress. Genie will be a library that implements the MPEG-G standard series. With Genie it will be possible to generate compressed bitstreams which conform to the MPEG-G standard series, and thus can be decoded using the MPEG-G reference decoder software. Genie will comprise functionality for the transcoding of genomic information from the SAM/BAM formats to the MPEG-G format.
2: I am not sure if I fully understand your question. Maybe this helps: Genie will be able to handle both unaligned and aligned data. Genie can be used to implement an aligner that reads/writes MPEG-G compliant data.

**Comment by voges** [comment]
Thanks again for asking these questions. As I do not see further questions posed upon my initial reply I consider this issue solved, and I will close it.

**Comment by Abby3017** [comment]
Thanks for your reply. Currently your answer cleared our doubt.
